# Generated by Django 5.2.8 on 2025-11-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ecom',
            fields=[
                ('pro_ID', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=30)),
                ('cost', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=1)),
                ('expdate', models.DateTimeField()),
                ('helpcentre', models.EmailField(max_length=254)),
                ('shipdate', models.DateTimeField()),
            ],
        ),
    ]
